FROM node:19.3-alpine3.16 AS build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM nginx:1.23-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
CMD ["nginx", "-g", "daemon off;"]
