FROM node:19.3-alpine3.16 AS build
WORKDIR /app
COPY openapi.json ./
COPY . .
RUN npm install
RUN npm run build

FROM nginx:1.23-alpine
COPY --from=build /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
