services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    image: backend-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-people}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET:-ACCESS_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET:-REFRESH_SECRET}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
    ports:
      - ${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}
    volumes:
      - ./backend:/app

  postgres:
    env_file:
      - .env.dev
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-people}
    image: postgres:alpine
    ports: 
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-8000}
    env_file:
      - .env.dev
    image: frontend-dev
    ports: 
      - ${FRONTEND_PORT:-5173}:5173
    volumes:
      - ./frontend:/app

volumes:
  db-data:
    
