services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    image: backend-test
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people-test
      - POSTGRES_PORT=5433
      - ACCESS_TOKEN_SECRET=ACCESS_SECRET
      - REFRESH_TOKEN_SECRET=REFRESH_SECRET

  db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people-test
    image: postgres:alpine
    ports: 
      - 5433:5432
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
