services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    image: backend-test
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${TEST_POSTGRES_DB:-people-test}
      - POSTGRES_PORT=5432
      - ACCESS_TOKEN_SECRET=${TEST_ACCESS_TOKEN_SECRET:-ACCESS_SECRET}
      - REFRESH_TOKEN_SECRET=${TEST_REFRESH_TOKEN_SECRET:-REFRESH_SECRET}

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${TEST_POSTGRES_DB:-people-test}
    image: postgres:alpine
    ports: 
      - 5433:5432
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
