services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    image: backend-prod
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - BACKEND_PORT=8000
    ports:
      - 8000:8000
    restart: always 
    volumes:
      - backend:/app

  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:alpine
    ports: 
      - 5432:5432
    restart: always 
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: frontend-prod
    ports: 
      - 80:80
    restart: always 

volumes:
  backend:
  db-data:
