services:
  backend:
    image: toxec/people-backend:main
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - BACKEND_PORT=8000
    ports:
      - 8000:8000
    restart: always 
    volumes:
      - .:/backend/app

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:15.1-alpine
    ports: 
      - 5432:5432
    restart: always 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    image: toxec/people-frontend:main
    ports: 
      - 80:80
    restart: always 
    volumes:
      - .:/frontend/app

volumes:
  db-data:
