services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend-dev
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people
      - POSTGRES_PORT=5432
      - ACCESS_TOKEN_SECRET=ACCESS_SECRET
      - REFRESH_TOKEN_SECRET=REFRESH_SECRET
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=people
    image: postgres:alpine
    ports: 
      - 5432:5432
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend-dev
    ports: 
      - 5173:5173
    volumes:
      - ./frontend:/app

volumes:
  db-data:
    
