services:
  backend:
    image: toxec/people-backend:main
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: always 
    volumes:
      - ./backend:/app

  db:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:alpine
    ports: 
      - ${POSTGRES_PORT}:5432
    restart: always 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  frontend:
    image: toxec/people-frontend:main
    ports: 
      - 80:80
    restart: always 
    volumes:
      - ./frontend:/app

volumes:
  db-data:
