[build]
  cmd = "go generate ./... && go build -o ./tmp/main cmd/main.go"
  include_ext = ["go", "json", "yaml"]
  exclude_file = ["spec.gen.go", "models.gen.go", "errorkind_string.go"]
  exclude_dir = ["images"]
