FROM golang:alpine
WORKDIR /app
RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
COPY openapi.json ./
COPY go.mod ./
COPY go.sum ./
RUN go mod download
CMD ["air"]
