FROM golang:1.19-alpine3.17 AS build
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" cmd/main.go

FROM scratch
COPY --from=build /app/main /
CMD ["/main"]
