// Package people provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package people

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Handle   string   `fake:"{lettern:10}" json:"handle"`
	Password Password `fake:"{password:true,true,true,true,false,12}" json:"password"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Tokens defines model for Tokens.
type Tokens struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
}

// User defines model for User.
type User struct {
	Handle   string `db:"handle" json:"handle"`
	Hash     string `db:"hash" json:"-"`
	ID       uint   `db:"user_id" fake:"skip" json:"-"`
	Password string `json:"-"`
}

// AuthUserBody defines model for AuthUserBody.
type AuthUserBody = AuthUser

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = AuthUserBody

// PostRegisterJSONRequestBody defines body for PostRegister for application/json ContentType.
type PostRegisterJSONRequestBody = AuthUserBody
