openapi: 3.0.0
info:
  version: 1.0.0
  title: People API
tags:
  - name: auth
  - name: me
  - name: following

paths:
  /register:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/AuthUserBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'

  /login:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/AuthUserBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'

  /refresh:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/TokensBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
          
  /me/following/{handle}:
    put:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: User is already followed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        409:
          description: User is not followed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Tokens:
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - refreshToken

    AuthUser:
      properties:
        handle:
          type: string
          minLength: 5
          maxLength: 15
          x-oapi-codegen-extra-tags:
            fake: '{lettern:10}'
        password:
          type: string
          format: password
          minLength: 12
          x-go-type: Password
          x-oapi-codegen-extra-tags:
            fake: '{password:true,true,true,true,false,12}'
      required:
        - handle
        - password

    User:
      properties:
        id:
          type: integer
          x-go-name: ID
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: user_id
            fake: skip
            json: '-'
        handle:
          type: string
          x-oapi-codegen-extra-tags:
            db: handle
        password:
          type: string
          x-oapi-codegen-extra-tags:
            json: '-'
        hash:
          type: string
          x-oapi-codegen-extra-tags:
            db: hash
            json: '-'
        followers:
          type: integer
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: followers
            fake: skip
        following:
          type: integer
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: following
            fake: skip
      required:
        - id
        - handle
        - password
        - hash
        - followers
        - following

    Error:
      properties:
        message:
          type: string
      required:
        - message

  requestBodies:
    AuthUserBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthUser'
              
    TokensBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tokens'

  parameters:
    handleParam:
      name: handle
      in: path
      required: true
      schema:
        type: string
        minLength: 5
        maxLength: 15

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NoContent:
      description: No Content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
     
    Unauthorized:
      description: Access token is missing
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Forbidden:
      description: Token is malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
