openapi: 3.0.0
info:
  version: 1.0.0
  title: People API
tags:
  - name: auth
  - name: me
  - name: following

paths:
  /register:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/AuthUserBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'

  /login:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/AuthUserBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'

  /refresh:
    post:
      tags:
        - auth
      requestBody:
        $ref: '#/components/requestBodies/TokensBody'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'

  /me/following/{handle}:
    put:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        409:
          description: User is already followed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        409:
          description: User is not followed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'

  /me/followers/{handle}:
    get:
      tags:
        - me
        - followers
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/handleParam'
      responses:
        204: 
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'

  /me/following:
    get:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'

  /me/followers:
    get:
      tags:
        - me
        - following
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/pageParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Tokens:
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - refreshToken

    AuthUser:
      properties:
        id:
          type: integer
          x-go-name: ID
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: user_id
            fake: skip
        handle:
          type: string
          minLength: 5
          maxLength: 15
          x-oapi-codegen-extra-tags:
            db: handle
            fake: '{lettern:10}'
        password:
          type: string
          format: password
          minLength: 12
          x-go-type: Password
          x-oapi-codegen-extra-tags:
            fake: '{password:true,true,true,true,false,12}'
        hash:
          type: string
          x-oapi-codegen-extra-tags:
            db: hash
      required:
        - handle
        - password

    User:
      properties:
        handle:
          type: string
          x-oapi-codegen-extra-tags:
            db: handle
        followers:
          type: integer
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: followers
            fake: skip
        following:
          type: integer
          x-go-type: uint
          x-oapi-codegen-extra-tags:
            db: following
            fake: skip
      x-go-json-ignore:
        - password
        - hash
      required:
        - id
        - handle
        - password
        - hash
        - followers
        - following

    Error:
      properties:
        message:
          type: string
      required:
        - message

    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'

  requestBodies:
    AuthUserBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthUser'

    TokensBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tokens'

  parameters:
    handleParam:
      name: handle
      in: path
      required: true
      schema:
        type: string
        minLength: 5
        maxLength: 15

    pageParam:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        x-go-type: uint

    limitParam:
      name: limit
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        x-go-type: uint

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NoContent:
      description: No Content
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Access token is missing
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Forbidden:
      description: Token is malformed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
