/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Handle } from "./handle";
import type { AuthUserAllOf } from "./authUserAllOf";

export type AuthUser = Handle & AuthUserAllOf;
