/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */

export interface Follows {
	followers: number;
	following: number;
	isFollowing: boolean;
	isFollowed: boolean;
}
