/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { BeforeParamParameter } from "./beforeParamParameter";
import type { AfterParamParameter } from "./afterParamParameter";

export type GetMessagesLatestParams = {
	before?: BeforeParamParameter;
	after?: AfterParamParameter;
};
