/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryParamParameter } from "./queryParamParameter";
import type { LimitParamParameter } from "./limitParamParameter";
import type { BeforeParamParameter } from "./beforeParamParameter";
import type { AfterParamParameter } from "./afterParamParameter";

export type GetPostsSearchParams = {
	query: QueryParamParameter;
	limit?: LimitParamParameter;
	before?: BeforeParamParameter;
	after?: AfterParamParameter;
};
