/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { LimitParamParameter } from "@/models/limitParamParameter";
import type { BeforeParamParameter } from "@/models/beforeParamParameter";
import type { AfterParamParameter } from "@/models/afterParamParameter";

export type GetUsersHandlePostsParams = {
	limit?: LimitParamParameter;
	before?: BeforeParamParameter;
	after?: AfterParamParameter;
};
