/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryParamParameter } from "./queryParamParameter";
import type { LimitParamParameter } from "./limitParamParameter";
import type { BeforeHandleParamParameter } from "./beforeHandleParamParameter";
import type { AfterHandleParamParameter } from "./afterHandleParamParameter";

export type GetUsersSearchParams = {
	query: QueryParamParameter;
	limit?: LimitParamParameter;
	before?: BeforeHandleParamParameter;
	after?: AfterHandleParamParameter;
};
