/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryParamParameter } from "@/models/queryParamParameter";
import type { LimitParamParameter } from "@/models/limitParamParameter";
import type { BeforeHandleParamParameter } from "@/models/beforeHandleParamParameter";
import type { AfterHandleParamParameter } from "@/models/afterHandleParamParameter";

export type GetUsersSearchParams = {
	query: QueryParamParameter;
	limit?: LimitParamParameter;
	before?: BeforeHandleParamParameter;
	after?: AfterHandleParamParameter;
};
