/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";

export interface Message {
	id: number;
	content: string;
	from: User;
	threadID: number;
	sentAt: string;
}
