/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from "@/models/message";
import type { IDPaginationMeta } from "@/models/iDPaginationMeta";

export type MessageResults = {
	data: Message[];
	meta?: IDPaginationMeta;
};
