/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from "./message";
import type { IDPaginationMeta } from "./iDPaginationMeta";

export interface Messages {
	data: Message[];
	meta?: IDPaginationMeta;
}
