/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from "@/models/post";
import type { IDPaginationMeta } from "@/models/iDPaginationMeta";

export type Posts = {
	data: Post[];
	meta?: IDPaginationMeta;
};
