/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { PostRegister200UserStatus } from "./postRegister200UserStatus";

export type PostRegister200User = {
	handle: string;
	following: number;
	followers: number;
	status?: PostRegister200UserStatus;
};
