/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Posts } from "@/models/posts";

/**
 * OK
 */
export type PostsResponseResponse = Posts;
