/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from "./post";
import type { IDPaginationMeta } from "./iDPaginationMeta";

export interface Posts {
	data: Post[];
	meta?: IDPaginationMeta;
}
