/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { PostRegister200Tokens } from "./postRegister200Tokens";
import type { PostRegister200User } from "./postRegister200User";

export type PostRegister200 = {
	tokens: PostRegister200Tokens;
	user: PostRegister200User;
};
