/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from "./post";
import type { User } from "./user";

export interface PostResponse {
	data: Post;
	user: User;
}
