/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Message } from "./message";

export interface ServerMessage {
	message: Message;
	id: number;
	from: string;
	to: string;
	sentAt: string;
}
