/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "@/models/user";
import type { Message } from "@/models/message";

export type Thread = {
	id: number;
	users: User[];
	latest?: Message;
};
