/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Tokens } from "@/models/tokens";

/**
 * OK
 */
export type TokensResponse = Tokens;
