/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "./user";
import type { MessageResults } from "./messageResults";

export interface UserMessages {
	user: User;
	data: MessageResults;
}
