/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { User } from "@/models/user";
import type { HandlePaginationMeta } from "@/models/handlePaginationMeta";

export type Users = {
	data: User[];
	meta?: HandlePaginationMeta;
};
