/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Follows } from "./follows";
import type { UserAllOf } from "./userAllOf";

export type User = Follows & UserAllOf;
