/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import type { Users } from "@/models/users";

/**
 * OK
 */
export type UsersResponse = Users;
