openapi: 3.0.0
info:
  version: 1.0.0
  title: People API
servers:
  - url: /api

paths:
  /register:
    $ref: './paths/auth.yaml#/register'

  /login:
    $ref: './paths/auth.yaml#/login'

  /refresh:
    $ref: './paths/auth.yaml#/refresh'

  /logout:
    $ref: './paths/auth.yaml#/logout'

  /me:
    $ref: './paths/me.yaml#/profile'

  /me/feed:
    $ref: './paths/me.yaml#/feed'

  /me/following/{handle}:
    $ref: './paths/me.yaml#/followingByHandle'

  /me/following:
    $ref: './paths/me.yaml#/following'

  /me/followers:
    $ref: './paths/me.yaml#/followers'

  /users/{handle}:
    $ref: './paths/users.yaml#/user'

  /users/{handle}/following:
    $ref: './paths/users.yaml#/following'

  /users/{handle}/followers:
    $ref: './paths/users.yaml#/followers'

  /users/search:
    $ref: './paths/users.yaml#/search'

  /users/{handle}/posts:
    $ref: './paths/posts.yaml#/userPosts'

  /users/{handle}/likes:
    $ref: './paths/likes.yaml#/userLikes'

  /posts:
    $ref: './paths/posts.yaml#/posts'

  /posts/{postID}:
    $ref: './paths/posts.yaml#/post'

  /posts/search:
    $ref: './paths/posts.yaml#/search'

  /posts/{postID}/replies:
    $ref: './paths/replies.yaml#/replies'

  /posts/{postID}/likes:
    $ref: './paths/likes.yaml#/postLikes'

  /images:
    $ref: './paths/images.yaml#/images'

  /users/{handle}/thread:
    $ref: './paths/messages.yaml#/userThread'

  /threads:
    $ref: './paths/messages.yaml#/threads'

  /threads/{threadID}:
    $ref: './paths/messages.yaml#/thread'

  /threads/{threadID}/messages:
    $ref: './paths/messages.yaml#/threadMessages'

components: 
  $ref: './components/main.yaml#/components'
