/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * People API
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse, AxiosError } from "axios";
import { useQuery, useMutation } from "@tanstack/react-query";
import type {
	UseQueryOptions,
	UseMutationOptions,
	QueryFunction,
	MutationFunction,
	UseQueryResult,
	QueryKey,
} from "@tanstack/react-query";
import type {
	Tokens,
	BadRequestResponse,
	AuthUserBodyBody,
	UnauthorizedResponse,
	ForbiddenResponse,
	TokensBodyBody,
	NoContentResponse,
	NotFoundResponse,
	Error,
	Users,
	GetMeFollowingParams,
	GetMeFollowersParams,
	GetUsersHandleFollowingParams,
	GetUsersHandleFollowersParams,
	Post,
	PostBodyBody,
	Posts,
	GetPostsPostIDRepliesParams,
	GetUsersHandlePostsParams,
	GetMeFeedParams,
	Likes,
} from "./models";

export const postRegister = (
	authUserBodyBody: AuthUserBodyBody,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Tokens>> => {
	return axios.post(`/register`, authUserBodyBody, options);
};

export type PostRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof postRegister>>
>;
export type PostRegisterMutationBody = AuthUserBodyBody;
export type PostRegisterMutationError = AxiosError<BadRequestResponse>;

export const usePostRegister = <
	TError = AxiosError<BadRequestResponse>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postRegister>>,
		TError,
		{ data: AuthUserBodyBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postRegister>>,
		{ data: AuthUserBodyBody }
	> = (props) => {
		const { data } = props ?? {};

		return postRegister(data, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof postRegister>>,
		TError,
		{ data: AuthUserBodyBody },
		TContext
	>(mutationFn, mutationOptions);
};

export const postLogin = (
	authUserBodyBody: AuthUserBodyBody,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Tokens>> => {
	return axios.post(`/login`, authUserBodyBody, options);
};

export type PostLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof postLogin>>
>;
export type PostLoginMutationBody = AuthUserBodyBody;
export type PostLoginMutationError = AxiosError<
	BadRequestResponse | UnauthorizedResponse
>;

export const usePostLogin = <
	TError = AxiosError<BadRequestResponse | UnauthorizedResponse>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postLogin>>,
		TError,
		{ data: AuthUserBodyBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postLogin>>,
		{ data: AuthUserBodyBody }
	> = (props) => {
		const { data } = props ?? {};

		return postLogin(data, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof postLogin>>,
		TError,
		{ data: AuthUserBodyBody },
		TContext
	>(mutationFn, mutationOptions);
};

export const postRefresh = (
	tokensBodyBody: TokensBodyBody,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Tokens>> => {
	return axios.post(`/refresh`, tokensBodyBody, options);
};

export type PostRefreshMutationResult = NonNullable<
	Awaited<ReturnType<typeof postRefresh>>
>;
export type PostRefreshMutationBody = TokensBodyBody;
export type PostRefreshMutationError = AxiosError<
	BadRequestResponse | ForbiddenResponse
>;

export const usePostRefresh = <
	TError = AxiosError<BadRequestResponse | ForbiddenResponse>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postRefresh>>,
		TError,
		{ data: TokensBodyBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postRefresh>>,
		{ data: TokensBodyBody }
	> = (props) => {
		const { data } = props ?? {};

		return postRefresh(data, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof postRefresh>>,
		TError,
		{ data: TokensBodyBody },
		TContext
	>(mutationFn, mutationOptions);
};

export const putMeFollowingHandle = (
	handle: string,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<NoContentResponse>> => {
	return axios.put(`/me/following/${handle}`, undefined, options);
};

export type PutMeFollowingHandleMutationResult = NonNullable<
	Awaited<ReturnType<typeof putMeFollowingHandle>>
>;

export type PutMeFollowingHandleMutationError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
	| Error
>;

export const usePutMeFollowingHandle = <
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
		| Error
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putMeFollowingHandle>>,
		TError,
		{ handle: string },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putMeFollowingHandle>>,
		{ handle: string }
	> = (props) => {
		const { handle } = props ?? {};

		return putMeFollowingHandle(handle, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof putMeFollowingHandle>>,
		TError,
		{ handle: string },
		TContext
	>(mutationFn, mutationOptions);
};

export const deleteMeFollowingHandle = (
	handle: string,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<NoContentResponse>> => {
	return axios.delete(`/me/following/${handle}`, options);
};

export type DeleteMeFollowingHandleMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteMeFollowingHandle>>
>;

export type DeleteMeFollowingHandleMutationError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
>;

export const useDeleteMeFollowingHandle = <
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteMeFollowingHandle>>,
		TError,
		{ handle: string },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteMeFollowingHandle>>,
		{ handle: string }
	> = (props) => {
		const { handle } = props ?? {};

		return deleteMeFollowingHandle(handle, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof deleteMeFollowingHandle>>,
		TError,
		{ handle: string },
		TContext
	>(mutationFn, mutationOptions);
};

export const getMeFollowingHandle = (
	handle: string,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<NoContentResponse>> => {
	return axios.get(`/me/following/${handle}`, options);
};

export const getGetMeFollowingHandleQueryKey = (handle: string) => [
	`/me/following/${handle}`,
];

export type GetMeFollowingHandleQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeFollowingHandle>>
>;
export type GetMeFollowingHandleQueryError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
>;

export const useGetMeFollowingHandle = <
	TData = Awaited<ReturnType<typeof getMeFollowingHandle>>,
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
	>
>(
	handle: string,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getMeFollowingHandle>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMeFollowingHandleQueryKey(handle);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMeFollowingHandle>>
	> = ({ signal }) => getMeFollowingHandle(handle, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getMeFollowingHandle>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!handle,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const getMeFollowersHandle = (
	handle: string,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<NoContentResponse>> => {
	return axios.get(`/me/followers/${handle}`, options);
};

export const getGetMeFollowersHandleQueryKey = (handle: string) => [
	`/me/followers/${handle}`,
];

export type GetMeFollowersHandleQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeFollowersHandle>>
>;
export type GetMeFollowersHandleQueryError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
>;

export const useGetMeFollowersHandle = <
	TData = Awaited<ReturnType<typeof getMeFollowersHandle>>,
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
	>
>(
	handle: string,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getMeFollowersHandle>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMeFollowersHandleQueryKey(handle);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMeFollowersHandle>>
	> = ({ signal }) => getMeFollowersHandle(handle, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getMeFollowersHandle>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!handle,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const getMeFollowing = (
	params?: GetMeFollowingParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Users>> => {
	return axios.get(`/me/following`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetMeFollowingQueryKey = (params?: GetMeFollowingParams) => [
	`/me/following`,
	...(params ? [params] : []),
];

export type GetMeFollowingQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeFollowing>>
>;
export type GetMeFollowingQueryError = AxiosError<
	UnauthorizedResponse | ForbiddenResponse
>;

export const useGetMeFollowing = <
	TData = Awaited<ReturnType<typeof getMeFollowing>>,
	TError = AxiosError<UnauthorizedResponse | ForbiddenResponse>
>(
	params?: GetMeFollowingParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getMeFollowing>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeFollowingQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeFollowing>>> = ({
		signal,
	}) => getMeFollowing(params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getMeFollowing>>,
		TError,
		TData
	>(queryKey, queryFn, queryOptions) as UseQueryResult<TData, TError> & {
		queryKey: QueryKey;
	};

	query.queryKey = queryKey;

	return query;
};

export const getMeFollowers = (
	params?: GetMeFollowersParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Users>> => {
	return axios.get(`/me/followers`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetMeFollowersQueryKey = (params?: GetMeFollowersParams) => [
	`/me/followers`,
	...(params ? [params] : []),
];

export type GetMeFollowersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeFollowers>>
>;
export type GetMeFollowersQueryError = AxiosError<
	UnauthorizedResponse | ForbiddenResponse
>;

export const useGetMeFollowers = <
	TData = Awaited<ReturnType<typeof getMeFollowers>>,
	TError = AxiosError<UnauthorizedResponse | ForbiddenResponse>
>(
	params?: GetMeFollowersParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getMeFollowers>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeFollowersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeFollowers>>> = ({
		signal,
	}) => getMeFollowers(params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getMeFollowers>>,
		TError,
		TData
	>(queryKey, queryFn, queryOptions) as UseQueryResult<TData, TError> & {
		queryKey: QueryKey;
	};

	query.queryKey = queryKey;

	return query;
};

export const getUsersHandleFollowing = (
	handle: string,
	params?: GetUsersHandleFollowingParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Users>> => {
	return axios.get(`/users/${handle}/following`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetUsersHandleFollowingQueryKey = (
	handle: string,
	params?: GetUsersHandleFollowingParams
) => [`/users/${handle}/following`, ...(params ? [params] : [])];

export type GetUsersHandleFollowingQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersHandleFollowing>>
>;
export type GetUsersHandleFollowingQueryError = AxiosError<
	BadRequestResponse | NotFoundResponse
>;

export const useGetUsersHandleFollowing = <
	TData = Awaited<ReturnType<typeof getUsersHandleFollowing>>,
	TError = AxiosError<BadRequestResponse | NotFoundResponse>
>(
	handle: string,
	params?: GetUsersHandleFollowingParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getUsersHandleFollowing>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetUsersHandleFollowingQueryKey(handle, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersHandleFollowing>>
	> = ({ signal }) =>
		getUsersHandleFollowing(handle, params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getUsersHandleFollowing>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!handle,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const getUsersHandleFollowers = (
	handle: string,
	params?: GetUsersHandleFollowersParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Users>> => {
	return axios.get(`/users/${handle}/followers`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetUsersHandleFollowersQueryKey = (
	handle: string,
	params?: GetUsersHandleFollowersParams
) => [`/users/${handle}/followers`, ...(params ? [params] : [])];

export type GetUsersHandleFollowersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersHandleFollowers>>
>;
export type GetUsersHandleFollowersQueryError = AxiosError<
	BadRequestResponse | NotFoundResponse
>;

export const useGetUsersHandleFollowers = <
	TData = Awaited<ReturnType<typeof getUsersHandleFollowers>>,
	TError = AxiosError<BadRequestResponse | NotFoundResponse>
>(
	handle: string,
	params?: GetUsersHandleFollowersParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getUsersHandleFollowers>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetUsersHandleFollowersQueryKey(handle, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersHandleFollowers>>
	> = ({ signal }) =>
		getUsersHandleFollowers(handle, params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getUsersHandleFollowers>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!handle,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const postPosts = (
	postBodyBody: PostBodyBody,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Post>> => {
	return axios.post(`/posts`, postBodyBody, options);
};

export type PostPostsMutationResult = NonNullable<
	Awaited<ReturnType<typeof postPosts>>
>;
export type PostPostsMutationBody = PostBodyBody;
export type PostPostsMutationError = AxiosError<
	BadRequestResponse | UnauthorizedResponse | ForbiddenResponse
>;

export const usePostPosts = <
	TError = AxiosError<
		BadRequestResponse | UnauthorizedResponse | ForbiddenResponse
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postPosts>>,
		TError,
		{ data: PostBodyBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postPosts>>,
		{ data: PostBodyBody }
	> = (props) => {
		const { data } = props ?? {};

		return postPosts(data, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof postPosts>>,
		TError,
		{ data: PostBodyBody },
		TContext
	>(mutationFn, mutationOptions);
};

export const getPostsPostID = (
	postID: number,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Post>> => {
	return axios.get(`/posts/${postID}`, options);
};

export const getGetPostsPostIDQueryKey = (postID: number) => [
	`/posts/${postID}`,
];

export type GetPostsPostIDQueryResult = NonNullable<
	Awaited<ReturnType<typeof getPostsPostID>>
>;
export type GetPostsPostIDQueryError = AxiosError<
	BadRequestResponse | NotFoundResponse
>;

export const useGetPostsPostID = <
	TData = Awaited<ReturnType<typeof getPostsPostID>>,
	TError = AxiosError<BadRequestResponse | NotFoundResponse>
>(
	postID: number,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getPostsPostID>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetPostsPostIDQueryKey(postID);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getPostsPostID>>> = ({
		signal,
	}) => getPostsPostID(postID, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getPostsPostID>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!postID,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const deletePostsPostID = (
	postID: number,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<NoContentResponse>> => {
	return axios.delete(`/posts/${postID}`, options);
};

export type DeletePostsPostIDMutationResult = NonNullable<
	Awaited<ReturnType<typeof deletePostsPostID>>
>;

export type DeletePostsPostIDMutationError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
>;

export const useDeletePostsPostID = <
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deletePostsPostID>>,
		TError,
		{ postID: number },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deletePostsPostID>>,
		{ postID: number }
	> = (props) => {
		const { postID } = props ?? {};

		return deletePostsPostID(postID, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof deletePostsPostID>>,
		TError,
		{ postID: number },
		TContext
	>(mutationFn, mutationOptions);
};

export const postPostsPostIDReplies = (
	postID: number,
	postBodyBody: PostBodyBody,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Post>> => {
	return axios.post(`/posts/${postID}/replies`, postBodyBody, options);
};

export type PostPostsPostIDRepliesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postPostsPostIDReplies>>
>;
export type PostPostsPostIDRepliesMutationBody = PostBodyBody;
export type PostPostsPostIDRepliesMutationError = AxiosError<
	| BadRequestResponse
	| UnauthorizedResponse
	| ForbiddenResponse
	| NotFoundResponse
>;

export const usePostPostsPostIDReplies = <
	TError = AxiosError<
		| BadRequestResponse
		| UnauthorizedResponse
		| ForbiddenResponse
		| NotFoundResponse
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postPostsPostIDReplies>>,
		TError,
		{ postID: number; data: PostBodyBody },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postPostsPostIDReplies>>,
		{ postID: number; data: PostBodyBody }
	> = (props) => {
		const { postID, data } = props ?? {};

		return postPostsPostIDReplies(postID, data, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof postPostsPostIDReplies>>,
		TError,
		{ postID: number; data: PostBodyBody },
		TContext
	>(mutationFn, mutationOptions);
};

export const getPostsPostIDReplies = (
	postID: number,
	params?: GetPostsPostIDRepliesParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Posts>> => {
	return axios.get(`/posts/${postID}/replies`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetPostsPostIDRepliesQueryKey = (
	postID: number,
	params?: GetPostsPostIDRepliesParams
) => [`/posts/${postID}/replies`, ...(params ? [params] : [])];

export type GetPostsPostIDRepliesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getPostsPostIDReplies>>
>;
export type GetPostsPostIDRepliesQueryError = AxiosError<unknown>;

export const useGetPostsPostIDReplies = <
	TData = Awaited<ReturnType<typeof getPostsPostIDReplies>>,
	TError = AxiosError<unknown>
>(
	postID: number,
	params?: GetPostsPostIDRepliesParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getPostsPostIDReplies>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetPostsPostIDRepliesQueryKey(postID, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getPostsPostIDReplies>>
	> = ({ signal }) =>
		getPostsPostIDReplies(postID, params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getPostsPostIDReplies>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!postID,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const getUsersHandlePosts = (
	handle: string,
	params?: GetUsersHandlePostsParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Posts>> => {
	return axios.get(`/users/${handle}/posts`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetUsersHandlePostsQueryKey = (
	handle: string,
	params?: GetUsersHandlePostsParams
) => [`/users/${handle}/posts`, ...(params ? [params] : [])];

export type GetUsersHandlePostsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersHandlePosts>>
>;
export type GetUsersHandlePostsQueryError = AxiosError<unknown>;

export const useGetUsersHandlePosts = <
	TData = Awaited<ReturnType<typeof getUsersHandlePosts>>,
	TError = AxiosError<unknown>
>(
	handle: string,
	params?: GetUsersHandlePostsParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getUsersHandlePosts>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUsersHandlePostsQueryKey(handle, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersHandlePosts>>
	> = ({ signal }) =>
		getUsersHandlePosts(handle, params, { signal, ...axiosOptions });

	const query = useQuery<
		Awaited<ReturnType<typeof getUsersHandlePosts>>,
		TError,
		TData
	>(queryKey, queryFn, {
		enabled: !!handle,
		...queryOptions,
	}) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const getMeFeed = (
	params?: GetMeFeedParams,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Posts>> => {
	return axios.get(`/me/feed`, {
		...options,
		params: { ...params, ...options?.params },
	});
};

export const getGetMeFeedQueryKey = (params?: GetMeFeedParams) => [
	`/me/feed`,
	...(params ? [params] : []),
];

export type GetMeFeedQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMeFeed>>
>;
export type GetMeFeedQueryError = AxiosError<
	UnauthorizedResponse | ForbiddenResponse
>;

export const useGetMeFeed = <
	TData = Awaited<ReturnType<typeof getMeFeed>>,
	TError = AxiosError<UnauthorizedResponse | ForbiddenResponse>
>(
	params?: GetMeFeedParams,
	options?: {
		query?: UseQueryOptions<
			Awaited<ReturnType<typeof getMeFeed>>,
			TError,
			TData
		>;
		axios?: AxiosRequestConfig;
	}
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
	const { query: queryOptions, axios: axiosOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMeFeedQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeFeed>>> = ({
		signal,
	}) => getMeFeed(params, { signal, ...axiosOptions });

	const query = useQuery<Awaited<ReturnType<typeof getMeFeed>>, TError, TData>(
		queryKey,
		queryFn,
		queryOptions
	) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

	query.queryKey = queryKey;

	return query;
};

export const putPostsPostIDLikes = (
	postID: number,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Likes>> => {
	return axios.put(`/posts/${postID}/likes`, undefined, options);
};

export type PutPostsPostIDLikesMutationResult = NonNullable<
	Awaited<ReturnType<typeof putPostsPostIDLikes>>
>;

export type PutPostsPostIDLikesMutationError = AxiosError<
	UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | Error
>;

export const usePutPostsPostIDLikes = <
	TError = AxiosError<
		UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | Error
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putPostsPostIDLikes>>,
		TError,
		{ postID: number },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putPostsPostIDLikes>>,
		{ postID: number }
	> = (props) => {
		const { postID } = props ?? {};

		return putPostsPostIDLikes(postID, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof putPostsPostIDLikes>>,
		TError,
		{ postID: number },
		TContext
	>(mutationFn, mutationOptions);
};

export const deletePostsPostIDLikes = (
	postID: number,
	options?: AxiosRequestConfig
): Promise<AxiosResponse<Likes>> => {
	return axios.delete(`/posts/${postID}/likes`, options);
};

export type DeletePostsPostIDLikesMutationResult = NonNullable<
	Awaited<ReturnType<typeof deletePostsPostIDLikes>>
>;

export type DeletePostsPostIDLikesMutationError = AxiosError<
	UnauthorizedResponse | ForbiddenResponse | NotFoundResponse
>;

export const useDeletePostsPostIDLikes = <
	TError = AxiosError<
		UnauthorizedResponse | ForbiddenResponse | NotFoundResponse
	>,
	TContext = unknown
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deletePostsPostIDLikes>>,
		TError,
		{ postID: number },
		TContext
	>;
	axios?: AxiosRequestConfig;
}) => {
	const { mutation: mutationOptions, axios: axiosOptions } = options ?? {};

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deletePostsPostIDLikes>>,
		{ postID: number }
	> = (props) => {
		const { postID } = props ?? {};

		return deletePostsPostIDLikes(postID, axiosOptions);
	};

	return useMutation<
		Awaited<ReturnType<typeof deletePostsPostIDLikes>>,
		TError,
		{ postID: number },
		TContext
	>(mutationFn, mutationOptions);
};
